### PR TITLE
also bind mount files and symlinks

### PR DESCRIPTION
**Pull request by Mic92**
compiles but untested :)
Please have a look @valmar

### CODE REVIEW

**Comment by Mic92** [comment]
fixes https://github.com/nix-community/nix-user-chroot/issues/7

**Comment by valmar** [comment]
It works! Thank you so much!

**Comment by Mic92** [comment]
@valmar could you also create a regular file in / and see if it gets bind mounted properly into the chroot?

**Comment by valmar** [comment]
Sure! How could I verify it? with "./nix-user-chroot ~/.nix bash -c ls 
/file"?

Valerio

PS: If I don't answer immediately, I will be back in a couple of hours

**Comment by Mic92** [comment]
./nix-user-chroot ~/.nix cat /file

**Comment by valmar** [comment]
Sorry for the delay! It works!

**Pull request merged**
